apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
  labels:
    app: my-react-app
spec:
  replicas: 3 # Number of instances to run
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
      - name: my-react-app
        image: kunaln27/my-react-app:latest # The image you pushed to Docker Hub
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: "production" # Environment variable if needed
---
apiVersion: v1
kind: Service
metadata:
  name: my-react-app-service
spec:
  selector:
    app: my-react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # You can change this to ClusterIP or NodePort based on your needs
